# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Beautiful Minds Medical
email: contact@beautifulmindsmedical.com
description: Your mind is beautiful. We can help take care of it. We offer a variety of treatment options with one goal in mind - a healthier, happier you.

url: "https://www.beautifulmindsmedical.com" # the base hostname & protocol for your site, e.g. http://example.com
# url: "https://merciful-scissors.cloudvent.net"
twitter:
  username: DrBinus
  card: summary
github_username:  webpoint-solutions-llc

paginate: 10
paginate_path: "/blog/:num/"

# Build settings
theme: bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-debug
  - jekyll-sitemap
  - jekyll-redirect-from

  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

authors:
  - hawadmin
  - elise-harboldt
  - Kirsten Weir

permalink: /blog/:categories/:year/:month/:day/:title

collections:
  treatment-team:
    output: true
    permalink: /:collection/:name
    sort_by: order
  staff:
    output: true
    permalink: /:collection/:name
    sort_by: order
  testimonials:
    output: true
    permalink: /:collection/:name
    sort_by: order
  faqs:
    output: true
    permalink: /:collection/:name
    sort_by: order
  events:
    output: true
    permalink: /:collection/:name
    sort_by: order
  wellness-resources:
    # output: true
    permalink: /:collection/:name
    sort_by: order



